version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

build:
  publish_nuget: true

artifacts:
  - path: src\Utils\bin\Debug\Utils.dll
    name: dll

  - path: '**\*.nupkg'
    name: nuget
